package fi.aalto.radio

/** Provider spellings are separate from the labels and local word matching.
 * Each tag is an alternative: selecting Rock and Jazz never means Rock AND Jazz.
 */
internal fun genreSearchTags(labels: Set<String>): Set<String> = labels.flatMap { label ->
    when (label) {
        "Pop" -> listOf("pop", "top40", "charts", "hotac")
        "Rock" -> listOf("rock")
        "Dance & elektroninen" -> listOf("dance", "edm", "electronic", "elektroninen")
        "Hip-hop & R&B" -> listOf("hip", "rap", "rnb", "r&b")
        "Uutiset & puhe" -> listOf("news", "talk", "spoken", "uutiset", "puhe")
        "Klassinen" -> listOf("classical", "klassinen")
        "Jazz & soul" -> listOf("jazz", "soul")
        "Country & folk" -> listOf("country", "folk")
        "Lapset & perhe" -> listOf("children", "family", "lapset")
        "Vuosikymmenet" -> listOf("50s", "60s", "70s", "80s", "90s", "00s", "oldies", "retro")
        "Hitit" -> listOf("top40", "charts", "hits", "hit", "chr")
        "Iskelmä & schlager" -> listOf("iskelmä", "iskelma", "schlager")
        "Indie" -> listOf("indie")
        "Klassinen rock" -> listOf("classic")
        "Metalli" -> listOf("metal", "hardrock")
        "Alternatiivinen" -> listOf("alternative", "grunge")
        "Punk" -> listOf("punk")
        "60-luku" -> listOf("60s", "sixties")
        "70-luku" -> listOf("70s", "seventies")
        "80-luku" -> listOf("80s", "eighties")
        "90-luku" -> listOf("90s", "nineties")
        "2000-luku" -> listOf("00s", "2000s")
        "Oldies" -> listOf("oldies", "retro")
        "House" -> listOf("house")
        "Techno" -> listOf("techno")
        "Trance" -> listOf("trance")
        "Drum & bass" -> listOf("drum", "dnb")
        "Chillout & lounge" -> listOf("chill", "lounge", "ambient")
        "Hip-hop" -> listOf("hip", "rap")
        "R&B" -> listOf("rnb", "r&b")
        "Reggae" -> listOf("reggae", "dancehall")
        "Uutiset" -> listOf("news", "uutiset")
        "Puhe" -> listOf("talk", "spoken", "puhe")
        "Urheilu" -> listOf("sport", "urheilu")
        "Hengellinen" -> listOf("christian", "religious", "gospel", "worship")
        "Ooppera" -> listOf("opera", "ooppera")
        "Elokuvamusiikki" -> listOf("soundtrack", "film", "movie")
        "Jazz" -> listOf("jazz")
        "Blues" -> listOf("blues")
        "Soul & funk" -> listOf("soul", "funk", "motown")
        "Country" -> listOf("country")
        "Folk" -> listOf("folk", "kansanmusiikki")
        "Latin" -> listOf("latin", "salsa", "reggaeton")
        "Maailmanmusiikki" -> listOf("world")
        // "Other" is a local exclusion, not a tag in the station directory.
        else -> emptyList()
    }
}.toSet()
